In [3]:
# Airbnb Revenue Analysis

## 01 — Data Understanding

### Objective

#Understand the structure, quality, and key variables in the New York City Airbnb datasets before performing deeper cleaning and analysis.

### Dataset

#This notebook uses the detailed NYC listings dataset from Inside Airbnb.

### Initial Questions

#- How many listings and variables are included?
#- Which columns are most relevant to pricing and revenue?
#- Which important variables contain missing values?
#- Which variables need to be converted or cleaned?

# Import pandas for working with tabular data
import pandas as pd
# Load the compressed listings dataset
# The notebook is inside the notebooks folder, so ../ moves up to the main project folder
listings = pd.read_csv("../data/raw/listings.csv.gz")

In [4]:
# Display the first five rows to understand the general structure
listings.head()
# Return the number of rows and columns
listings.shape

<class 'pandas.DataFrame'>
RangeIndex: 30259 entries, 0 to 30258
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            30259 non-null  int64
 1   listing_url                                   30259 non-null  str
 2   scrape_id                                     30259 non-null  int64
 3   last_scraped                                  30259 non-null  str
 4   source                                        30259 non-null  str
 5   name                                          30258 non-null  str
 6   description                                   29357 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   30259 non-null  str
 9   host_id                                       30259 non-null  int64
 10  host_url                                      30259 non-null  str
 11  host_profile_id                               29910 non-null  float64
 12  host_profile_url                              29910 non-null  str
 13  host_name                                     29910 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      29910 non-null  float64
 16  hosts_time_as_user_months                     29910 non-null  float64
 17  hosts_time_as_host_years                      29910 non-null  float64
 18  hosts_time_as_host_months                     29910 non-null  float64
 19  host_location                                 23097 non-null  str
 20  host_about                                    17849 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             29910 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              29910 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           29910 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          29910 non-null  str
 32  host_identity_verified                        29910 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        30259 non-null  str
 35  neighbourhood_group_cleansed                  30259 non-null  str
 36  latitude                                      30259 non-null  float64
 37  longitude                                     30259 non-null  float64
 38  property_type                                 30259 non-null  str
 39  room_type                                     30259 non-null  str
 40  accommodates                                  30259 non-null  int64
 41  bathrooms                                     20147 non-null  float64
 42  bathrooms_text                                30100 non-null  str
 43  bedrooms                                      19286 non-null  float64
 44  beds                                          20839 non-null  float64
 45  amenities                                     30259 non-null  str
 46  price                                         21515 non-null  str
 47  price_quote_checkin_date                      22678 non-null  str
 48  price_quote_checkout_date                     22678 non-null  str
 49  price_quote_total_price                       21514 non-null  float64
 50  price_quote_price_per_night                   21514 non-null  float64
 51  price_quote_raw                               22678 non-null  str
 52  minimum_nights                                30257 non-null  float64
 53  maximum_nights                                30257 non-null  float64
 54  minimum_minimum_nights                        30257 non-null  float64
 55  maximum_minimum_nights                        30257 non-null  float64
 56  minimum_maximum_nights                        30257 non-null  float64
 57  maximum_maximum_nights                        30257 non-null  float64
 58  minimum_nights_avg_ntm                        30259 non-null  float64
 59  maximum_nights_avg_ntm                        30259 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29912 non-null  str
 62  availability_30                               30259 non-null  int64
 63  availability_60                               30259 non-null  int64
 64  availability_90                               30259 non-null  int64
 65  availability_365                              30259 non-null  int64
 66  calendar_last_scraped                         30259 non-null  str
 67  number_of_reviews                             30259 non-null  int64
 68  number_of_reviews_ltm                         30259 non-null  int64
 69  number_of_reviews_l30d                        30259 non-null  int64
 70  availability_eoy                              30259 non-null  int64
 71  number_of_reviews_ly                          30259 non-null  int64
 72  estimated_occupancy_l365d                     30259 non-null  int64
 73  estimated_revenue_l365d                       21515 non-null  float64
 74  first_review                                  21700 non-null  str
 75  last_review                                   21700 non-null  str
 76  review_scores_rating                          21700 non-null  float64
 77  review_scores_accuracy                        21694 non-null  float64
 78  review_scores_cleanliness                     21700 non-null  float64
 79  review_scores_checkin                         21692 non-null  float64
 80  review_scores_communication                   21697 non-null  float64
 81  review_scores_location                        21691 non-null  float64
 82  review_scores_value                           21691 non-null  float64
 83  license                                       5286 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                30259 non-null  int64
 86  calculated_host_listings_count_entire_homes   30259 non-null  int64
 87  calculated_host_listings_count_private_rooms  30259 non-null  int64
 88  calculated_host_listings_count_shared_rooms   30259 non-null  int64
 89  reviews_per_month                             21700 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 20.8 MB

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.025900e+04,3.025900e+04,0.0,3.025900e+04,2.991000e+04,0.0,29910.000000,29910.000000,29910.000000,29910.000000,...,21692.000000,21697.000000,21691.000000,21691.000000,0.0,30259.000000,30259.000000,30259.000000,30259.000000,21700.000000
mean,6.172513e+17,2.026061e+13,NaN,2.672815e+15,1.469574e+18,NaN,8.284754,5.653928,6.684286,5.631829,...,4.838066,4.821284,4.743640,4.633094,NaN,55.887141,45.630721,9.146601,0.095905,0.846505
std,6.155147e+17,0.000000e+00,NaN,6.705743e+16,2.417060e+16,NaN,3.934796,3.482520,3.889389,3.356700,...,0.373301,0.418090,0.388374,0.496439,NaN,174.246090,172.331916,36.412035,1.125182,1.847935
min,2.539000e+03,2.026061e+13,NaN,1.678000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.038760e+07,2.026061e+13,NaN,2.069159e+07,1.462882e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.827500,4.820000,4.660000,4.530000,NaN,1.000000,0.000000,0.000000,0.000000,0.090000
50%,6.608782e+17,2.026061e+13,NaN,1.074344e+08,1.465524e+18,NaN,9.000000,6.000000,7.000000,5.000000,...,4.950000,4.960000,4.850000,4.760000,NaN,2.000000,1.000000,0.000000,0.000000,0.270000
75%,1.160901e+18,2.026061e+13,NaN,3.948700e+08,1.469572e+18,NaN,11.000000,9.000000,10.000000,8.000000,...,5.000000,5.000000,5.000000,4.920000,NaN,12.000000,3.000000,2.000000,0.000000,0.962500
max,1.707075e+18,2.026061e+13,NaN,1.704453e+18,1.706707e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,955.000000,955.000000,231.000000,22.000000,115.630000

In [5]:
# Display all available column names
list(listings.columns)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_profile_id',
 'host_profile_url',
 'host_name',
 'host_since',
 'hosts_time_as_user_years',
 'hosts_time_as_user_months',
 'hosts_time_as_host_years',
 'hosts_time_as_host_months',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_total_price',
 'price_quote_price_per_night',
 'price_quote_raw',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [6]:
## Key Variables for Analysis
important_columns = [
    "price",
    "room_type",
    "property_type",
    "accommodates",
    "bedrooms",
    "beds",
    "bathrooms_text",
    "amenities",
    "host_is_superhost",
    "review_scores_rating",
    "number_of_reviews",
    "availability_365",
    "neighbourhood_cleansed"
]

listings[important_columns].head()

,price,room_type,property_type,accommodates,bedrooms,beds,bathrooms_text,amenities,host_is_superhost,review_scores_rating,number_of_reviews,availability_365,neighbourhood_cleansed
0,$113.97,Private room,Private room in condo,2,1.0,2.0,1 shared bath,"[""Bed linens"", ""Hot water"", ""Exterior security...",f,4.80,10,339,Kensington
1,$117.27,Entire home/apt,Entire rental unit,3,2.0,1.0,1 bath,"[""Bed linens"", ""Hot water"", ""Fire extinguisher...",t,4.60,198,191,Williamsburg
2,$80.06,Private room,Private room in condo,1,NaN,1.0,1 shared bath,"[""Dryer"", ""Exterior security cameras on proper...",f,5.00,2,286,East Harlem
3,$77.17,Private room,Private room in rental unit,1,NaN,1.0,1 shared bath,"[""Bed linens"", ""Hot water"", ""Fire extinguisher...",t,4.88,251,218,East Harlem
4,$202.47,Private room,Private room in guest suite,2,NaN,2.0,1 private bath,"[""Bed linens"", ""Hot water"", ""Cleaning products...",t,4.89,423,106,Fort Greene

In [7]:
listings[important_columns].isnull().sum()

price                      8744
room_type                     0
property_type                 0
accommodates                  0
bedrooms                  10973
beds                       9420
bathrooms_text              159
amenities                     0
host_is_superhost           349
review_scores_rating       8559
number_of_reviews             0
availability_365              0
neighbourhood_cleansed        0
dtype: int64

In [8]:
listings[important_columns].dtypes

price                         str
room_type                     str
property_type                 str
accommodates                int64
bedrooms                  float64
beds                      float64
bathrooms_text                str
amenities                     str
host_is_superhost             str
review_scores_rating      float64
number_of_reviews           int64
availability_365            int64
neighbourhood_cleansed        str
dtype: object

In [9]:
listings["price"].head(20)

0     $113.97
1     $117.27
2      $80.06
3      $77.17
4     $202.47
5     $365.97
6     $154.87
7      $91.07
8         NaN
9         NaN
10        NaN
11    $159.77
12     $87.77
13        NaN
14     $72.00
15    $193.03
16    $148.04
17     $43.86
18    $118.07
19    $114.33
Name: price, dtype: str

In [14]:
# Convert price values into numbers
# 1. Convert all values to pandas' string type
# 2. Remove dollar signs
# 3. Remove commas from values such as $1,250.00
# 4. Convert the cleaned text into numeric values
# 5. Turn invalid or missing values into NA rather than causing an error
listings["price_clean"] = pd.to_numeric(
    listings["price"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

In [15]:
# Compare the original and cleaned price columns
listings[["price", "price_clean"]].head(10)

    price  price_clean
0  113.97       113.97
1  117.27       117.27
2   80.06        80.06
3   77.17        77.17
4  202.47       202.47
5  365.97       365.97
6  154.87       154.87
7   91.07        91.07
8     NaN         <NA>
9     NaN         <NA>

In [16]:
# Confirm that price_clean is numeric
listings["price_clean"].dtype

Float64Dtype()

In [17]:
# Count how many listings have a usable numeric price

listings["price_clean"].notna().sum()

np.int64(21515)

In [18]:
# Summary statistics for cleaned prices

listings["price_clean"].describe().round(2)

count     21515.0
mean       278.23
std        531.73
min          4.58
25%         96.88
50%        174.69
75%        302.72
max      30972.96
Name: price_clean, dtype: Float64

In [19]:
# Compare average prices across room types

room_type_summary = (
    listings.groupby("room_type")["price_clean"]
    .agg(
        listing_count="count",
        average_price="mean",
        median_price="median"
    )
    .round(2)
    .sort_values("average_price", ascending=False)
)

room_type_summary

                 listing_count  average_price  median_price
room_type
Hotel room                 480         721.57         447.0
Entire home/apt          11537         331.41        222.87
Private room              9306         191.78        102.96
Shared room                192         164.39         54.66

In [20]:
# Compare average prices across property types

property_summary = (
    listings.groupby("property_type")["price_clean"]
    .agg(
        listing_count="count",
        average_price="mean",
        median_price="median"
    )
    .round(2)
    .sort_values("average_price", ascending=False)
)

property_summary.head(15)

                            listing_count  average_price  median_price
property_type
Tower                                   3        8701.96       11061.8
Castle                                  1         2803.5        2803.5
Entire villa                            6        1214.57        333.46
Houseboat                               6         964.36        517.14
Private room in resort                 43         808.17         869.0
Private room                           18         766.35        217.08
Shared room in townhouse               10         610.79        243.25
Room in hotel                        1349         607.76         379.0
Room in serviced apartment             31         586.87         299.0
Shared room in condo                    4         559.07         85.34
Room in boutique hotel                191         542.51         405.0
Room in aparthotel                     59         504.71         342.4
Entire townhouse                      332         499.64        283.63
Entire serviced apartment             178         471.42        433.66
Entire loft                           254         450.94        275.25

In [21]:
# Display the 10 most expensive Airbnb listings

listings[
    [
        "name",
        "room_type",
        "property_type",
        "neighbourhood_cleansed",
        "price_clean"
    ]
].sort_values(
    "price_clean",
    ascending=False
).head(10)

,name,room_type,property_type,neighbourhood_cleansed,price_clean
29997,"260 West Broadway, Unit 1/2C",Entire home/apt,Entire rental unit,Tribeca,30972.96
22075,Opulent Midtown Retreat with White-Gloved Service,Hotel room,Room in hotel,Upper East Side,14864.0
22076,"Presidential Suite Park View King Bed, The Pierre",Hotel room,Room in hotel,Upper East Side,14864.0
798,Sunny Luxury Bedroom Guest Bathroom,Private room,Private room in rental unit,Murray Hill,12279.07
731,Enormous Chrysler-View Bedroom/Bath,Private room,Private room in rental unit,Midtown,12078.47
18034,North Gallery Café,Entire home/apt,Tower,Midtown,11061.8
18011,"Eighth House, State of the Art NYC Venue",Entire home/apt,Tower,Midtown,11061.8
28453,Walk to Empire State | Gym. Live Jazz. Bar On-...,Private room,Room in hotel,Murray Hill,10986.0
28450,Empire State Views | Bar. Live Jazz + City Views,Private room,Room in hotel,Midtown,10986.0
28452,Near Fifth Ave | Bar. Pet-Friendly + Fine Dining,Private room,Room in hotel,Midtown,10986.0

In [ ]:
# Key Takeaways

#This notebook explored the Airbnb NYC dataset to understand its structure before cleaning and modeling.

#Main observations:

#- The dataset contains 30,259 Airbnb listings.
#- Approximately 71% of listings have valid nightly prices.
#- The average nightly price is higher than the median, indicating a right-skewed distribution.
#- Entire homes and hotel rooms command significantly higher prices than private or shared rooms.
#- Property type appears to have a strong relationship with nightly price.
#- Several important variables contain missing values and will require cleaning before analysis.

#The next notebook focuses on data cleaning and feature engineering.