In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load cleaned dataset

listings = pd.read_csv("../data/listings_clean.csv")

In [3]:
# View dataset information

print("Shape:", listings.shape)
listings.info()

Shape: (21364, 92)
<class 'pandas.DataFrame'>
RangeIndex: 21364 entries, 0 to 21363
Data columns (total 92 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            21364 non-null  int64
 1   listing_url                                   21364 non-null  str
 2   scrape_id                                     21364 non-null  int64
 3   last_scraped                                  21364 non-null  str
 4   source                                        21364 non-null  str
 5   name                                          21364 non-null  str
 6   description                                   20828 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   21364 non-null  str
 9   host_id                                       21364 non-null  int64
 10  host_url                                      21364 non-null  str
 11  host_profile_id                               21086 non-null  float64
 12  host_profile_url                              21085 non-null  str
 13  host_name                                     21086 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      21086 non-null  float64
 16  hosts_time_as_user_months                     21086 non-null  float64
 17  hosts_time_as_host_years                      21086 non-null  float64
 18  hosts_time_as_host_months                     21086 non-null  float64
 19  host_location                                 15418 non-null  str
 20  host_about                                    12423 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             21364 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              21086 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           21086 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          21086 non-null  str
 32  host_identity_verified                        21086 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        21364 non-null  str
 35  neighbourhood_group_cleansed                  21364 non-null  str
 36  latitude                                      21364 non-null  float64
 37  longitude                                     21364 non-null  float64
 38  property_type                                 21364 non-null  str
 39  room_type                                     21364 non-null  str
 40  accommodates                                  21364 non-null  int64
 41  bathrooms                                     19021 non-null  float64
 42  bathrooms_text                                21364 non-null  str
 43  bedrooms                                      21364 non-null  float64
 44  beds                                          21364 non-null  float64
 45  amenities                                     21364 non-null  str
 46  price                                         21364 non-null  str
 47  price_quote_checkin_date                      21364 non-null  str
 48  price_quote_checkout_date                     21364 non-null  str
 49  price_quote_total_price                       21363 non-null  float64
 50  price_quote_price_per_night                   21363 non-null  float64
 51  price_quote_raw                               21364 non-null  str
 52  minimum_nights                                21363 non-null  float64
 53  maximum_nights                                21363 non-null  float64
 54  minimum_minimum_nights                        21363 non-null  float64
 55  maximum_minimum_nights                        21363 non-null  float64
 56  minimum_maximum_nights                        21363 non-null  float64
 57  maximum_maximum_nights                        21363 non-null  float64
 58  minimum_nights_avg_ntm                        21364 non-null  float64
 59  maximum_nights_avg_ntm                        21364 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              21362 non-null  str
 62  availability_30                               21364 non-null  int64
 63  availability_60                               21364 non-null  int64
 64  availability_90                               21364 non-null  int64
 65  availability_365                              21364 non-null  int64
 66  calendar_last_scraped                         21364 non-null  str
 67  number_of_reviews                             21364 non-null  int64
 68  number_of_reviews_ltm                         21364 non-null  int64
 69  number_of_reviews_l30d                        21364 non-null  int64
 70  availability_eoy                              21364 non-null  int64
 71  number_of_reviews_ly                          21364 non-null  int64
 72  estimated_occupancy_l365d                     21364 non-null  int64
 73  estimated_revenue_l365d                       21364 non-null  float64
 74  first_review                                  15394 non-null  str
 75  last_review                                   15394 non-null  str
 76  review_scores_rating                          21364 non-null  float64
 77  review_scores_accuracy                        15394 non-null  float64
 78  review_scores_cleanliness                     15394 non-null  float64
 79  review_scores_checkin                         15394 non-null  float64
 80  review_scores_communication                   15394 non-null  float64
 81  review_scores_location                        15393 non-null  float64
 82  review_scores_value                           15394 non-null  float64
 83  license                                       4682 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                21364 non-null  int64
 86  calculated_host_listings_count_entire_homes   21364 non-null  int64
 87  calculated_host_listings_count_private_rooms  21364 non-null  int64
 88  calculated_host_listings_count_shared_rooms   21364 non-null  int64
 89  reviews_per_month                             15394 non-null  float64
 90  price_clean                                   21364 non-null  float64
 91  has_rating                                    21364 non-null  bool
dtypes: bool(1), float64(43), int64(18), str(30)
memory usage: 14.9 MB

In [4]:
# Select features for modeling

features = [
    "accommodates",
    "bedrooms",
    "beds",
    "bathrooms",
    "review_scores_rating",
    "number_of_reviews",
    "availability_365",
    "room_type",
    "property_type"
]

model_data = listings[features + ["price_clean"]]

model_data.head()

,accommodates,bedrooms,beds,bathrooms,review_scores_rating,number_of_reviews,availability_365,room_type,property_type,price_clean
0,2,1.0,2.0,1.0,4.80,10,339,Private room,Private room in condo,113.97
1,3,2.0,1.0,1.0,4.60,198,191,Entire home/apt,Entire rental unit,117.27
2,1,0.0,1.0,1.0,5.00,2,286,Private room,Private room in condo,80.06
3,1,0.0,1.0,1.0,4.88,251,218,Private room,Private room in rental unit,77.17
4,2,0.0,2.0,1.0,4.89,423,106,Private room,Private room in guest suite,202.47

In [5]:
# Encode categorical variables

model_data = pd.get_dummies(
    model_data,
    columns=["room_type", "property_type"],
    drop_first=True
)

model_data.head()

,accommodates,bedrooms,beds,bathrooms,review_scores_rating,number_of_reviews,availability_365,price_clean,room_type_Hotel room,room_type_Private room,...,property_type_Shared room in condo,property_type_Shared room in guest suite,property_type_Shared room in guesthouse,property_type_Shared room in home,property_type_Shared room in rental unit,property_type_Shared room in serviced apartment,property_type_Shared room in townhouse,property_type_Shared room in villa,property_type_Tiny home,property_type_Tower
0,2,1.0,2.0,1.0,4.80,10,339,113.97,False,True,...,False,False,False,False,False,False,False,False,False,False
1,3,2.0,1.0,1.0,4.60,198,191,117.27,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1,0.0,1.0,1.0,5.00,2,286,80.06,False,True,...,False,False,False,False,False,False,False,False,False,False
3,1,0.0,1.0,1.0,4.88,251,218,77.17,False,True,...,False,False,False,False,False,False,False,False,False,False
4,2,0.0,2.0,1.0,4.89,423,106,202.47,False,True,...,False,False,False,False,False,False,False,False,False,False

In [6]:
# Check for missing values

model_data.isnull().sum().sort_values(ascending=False).head(10)

bathrooms                                           2343
accommodates                                           0
property_type_Private room in loft                     0
property_type_Private room in townhouse                0
property_type_Private room in tiny home                0
property_type_Private room in serviced apartment       0
property_type_Private room in resort                   0
property_type_Private room in rental unit              0
property_type_Private room in religious building       0
property_type_Private room in ranch                    0
dtype: int64

In [7]:
# Fill missing bathroom values

model_data["bathrooms"] = model_data["bathrooms"].fillna(
    model_data["bathrooms"].median()
)

model_data.isnull().sum().sort_values(ascending=False).head(10)

accommodates                                        0
property_type_Private room in vacation home         0
property_type_Private room in tiny home             0
property_type_Private room in serviced apartment    0
property_type_Private room in resort                0
property_type_Private room in rental unit           0
property_type_Private room in religious building    0
property_type_Private room in ranch                 0
property_type_Private room in loft                  0
property_type_Private room in kezhan                0
dtype: int64

In [8]:
# Save feature-engineered dataset

model_data.to_csv("../data/model_data.csv", index=False)